# Generated by Django 6.0.6 on 2026-06-09 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('food', 'food'), ('travel', 'travel'), ('bills', 'bills'), ('shopping', 'shopping'), ('other', 'other')], max_length=100)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('cash', 'cash'), ('upi', 'upi'), ('card', 'card'), ('bank_transfer', 'bank_transfer'), ('other', 'other')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
