# Generated by Django 6.0.6 on 2026-06-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_invest', models.CharField(choices=[('stock', 'stock'), ('mutual_fund', 'mutual_fund'), ('crypto', 'crypto'), ('fd', 'fd'), ('gold', 'gold'), ('other', 'other')], max_length=100)),
                ('amount_invest', models.FloatField()),
                ('platform', models.CharField(choices=[('zerodha', 'zerodha'), ('groww', 'groww'), ('upstox', 'upstox'), ('angelone', 'angelone'), ('icicidirect', 'icicidirect'), ('hdfcsecurities', 'hdfcsecurities'), ('paytammoney', 'paytammoney'), ('kuvera', 'kuvera'), ('etmoney', 'atmoney'), ('fd', 'fd'), ('rd', 'rd'), ('ppf', 'ppf'), ('hdfcbank', 'hdfcbank'), ('icicibank', 'icicibank'), ('indiapost', 'indiapost'), ('indmoney', 'indmoney'), ('vested', 'vested'), ('interactivebrocker', 'interactivebrocker'), ('other', 'other')], max_length=100)),
                ('returnio', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
