# Generated by Django 6.0.6 on 2026-06-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('source', models.CharField(choices=[('salary', 'salary'), ('freelance', 'freelance'), ('business', 'business'), ('intrest', 'intrest'), ('rentelincome', 'rentelincome'), ('other', 'other')], max_length=100)),
                ('date', models.DateField()),
                ('paymentmode', models.CharField(choices=[('bank', 'bank'), ('upi', 'upi'), ('cash', 'cash'), ('cheque', 'cheque'), ('other', 'other')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
